# Generated by Django 4.2.16 on 2025-11-24 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        # This migration exists to fix dependency ordering issues
        # between the custom accounts app and django-allauth account app
        # when using a custom user model.
        #
        # No operations needed - this migration just ensures proper ordering
        # in the migration history to resolve InconsistentMigrationHistory errors.
    ]