# Generated by Django 4.2.16 on 2025-11-24 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # This migration resolves dependency issues between the custom accounts app
        # and django-allauth's account app when using a custom user model.
        #
        # The dependency chain is:
        # 1. auth migrations (Django's built-in auth framework)
        # 2. accounts.0001_initial (our custom user model)
        # 3. This migration ensures proper ordering before allauth migrations run
        #
        # No operations needed - this migration just ensures proper ordering
        migrations.RunSQL("SELECT 1;")  # No-op migration to ensure it's applied
    ]