# Generated by Django 4.2.16 on 2025-11-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        # This migration fixes the ordering issue between django-allauth's account
        # app and our custom accounts app when using a custom user model.
        #
        # By explicitly depending only on accounts.0001_initial, we ensure that
        # our custom user model is fully migrated before any allauth migrations
        # that depend on it are applied.
        #
        # This resolves the InconsistentMigrationHistory error:
        # "Migration account.0001_initial is applied before its dependency accounts.0001_initial"
        migrations.RunSQL("SELECT 1;")  # No-op migration
    ]