# Generated by Django 4.2.16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fix_allauth_dependency'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_type', models.CharField(choices=[('otp', 'OTP Verification'), ('password_reset', 'Password Reset'), ('welcome', 'Welcome Email'), ('daily_reading', 'Daily Reading Notification'), ('report_ready', 'Report Ready Notification'), ('consultation_reminder', 'Consultation Reminder'), ('subscription_upgrade', 'Subscription Upgrade'), ('subscription_expiry', 'Subscription Expiry'), ('account_locked', 'Account Locked'), ('profile_update', 'Profile Update')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('body_html', models.TextField(help_text='HTML email body. Use {{variable_name}} for variable substitution.')),
                ('body_text', models.TextField(help_text='Plain text email body. Use {{variable_name}} for variable substitution.')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Available template variables as JSON object with descriptions')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'email_templates',
                'ordering': ['template_type'],
            },
        ),
    ]

