# Generated by Django 4.2.16 on 2025-12-26 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_analytics', models.BooleanField(default=True, help_text='Share anonymous usage analytics')),
                ('share_marketing', models.BooleanField(default=False, help_text='Receive marketing emails')),
                ('share_third_party', models.BooleanField(default=False, help_text='Share data with third-party services')),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends', 'Friends Only')], default='private', max_length=20)),
                ('data_retention_consent', models.BooleanField(default=True, help_text='Consent to data retention')),
                ('data_retention_period_days', models.IntegerField(default=365, help_text='Data retention period in days')),
                ('gdpr_consent', models.BooleanField(default=False, help_text='GDPR consent given')),
                ('gdpr_consent_date', models.DateTimeField(blank=True, null=True)),
                ('privacy_policy_accepted', models.BooleanField(default=False)),
                ('privacy_policy_version', models.CharField(blank=True, max_length=20, null=True)),
                ('privacy_policy_accepted_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Privacy Settings',
                'verbose_name_plural': 'Privacy Settings',
                'db_table': 'privacy_settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error'), ('report_ready', 'Report Ready'), ('daily_reading', 'Daily Reading'), ('compatibility_match', 'Compatibility Match'), ('consultation_reminder', 'Consultation Reminder'), ('new_message', 'New Message'), ('subscription', 'Subscription Updates'), ('payment', 'Payment Notifications')], max_length=50)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('push', 'Push Notification'), ('sms', 'SMS')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
                'indexes': [models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_a2f388_idx'), models.Index(fields=['user', 'enabled'], name='notificatio_user_id_4f7e97_idx')],
                'unique_together': {('user', 'notification_type', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('auth_login', 'Login'), ('auth_logout', 'Logout'), ('auth_register', 'Registration'), ('auth_password_reset', 'Password Reset'), ('payment_create', 'Payment Created'), ('payment_succeeded', 'Payment Succeeded'), ('payment_failed', 'Payment Failed'), ('subscription_create', 'Subscription Created'), ('subscription_update', 'Subscription Updated'), ('subscription_cancel', 'Subscription Canceled'), ('profile_update', 'Profile Updated'), ('data_access', 'Data Accessed'), ('data_export', 'Data Exported'), ('account_delete', 'Account Deleted')], db_index=True, max_length=50)),
                ('resource_type', models.CharField(choices=[('user', 'User'), ('payment', 'Payment'), ('subscription', 'Subscription'), ('report', 'Report'), ('consultation', 'Consultation')], db_index=True, max_length=50)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'), models.Index(fields=['action', 'timestamp'], name='audit_logs_action_474804_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_logs_resourc_bda8a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name/description for this API key', max_length=100)),
                ('key', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('key_prefix', models.CharField(editable=False, help_text='First 8 chars of key for display', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key'], name='api_keys_key_291dcc_idx'), models.Index(fields=['user', 'is_active'], name='accounts_api_keys_user_active_idx')],
            },
        ),
    ]
