# Generated by Django 4.2.16 on 2026-01-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_privacysettings_notificationpreference_auditlog_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apikey',
            new_name='api_keys_user_id_6e7352_idx',
            old_name='accounts_api_keys_user_active_idx',
        ),
    ]
