# Generated by Django 4.2.16 on 2025-11-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='content_template',
            field=models.TextField(default='', help_text='Template content for generating reports'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='required_data',
            field=models.JSONField(blank=True, default=dict, help_text='Required data fields for this template'),
        ),
    ]
