# Generated by Django 4.2.16 on 2025-11-25 07:30

from django.db import migrations


def create_default_report_templates(apps, schema_editor):
    ReportTemplate = apps.get_model('reports', 'ReportTemplate')
    
    # Create default templates
    templates = [
        {
            'name': 'Basic Birth Chart',
            'description': 'A comprehensive overview of your core numerology numbers including Life Path, Destiny, Soul Urge, and Personality numbers.',
            'report_type': 'basic',
            'is_premium': False,
            'is_active': True,
            'content_template': 'Basic birth chart template content'
        },
        {
            'name': 'Detailed Analysis',
            'description': 'An in-depth exploration of all your numerology numbers with detailed interpretations and personalized insights.',
            'report_type': 'detailed',
            'is_premium': True,
            'is_active': True,
            'content_template': 'Detailed analysis template content'
        },
        {
            'name': 'Compatibility Report',
            'description': 'Analyze compatibility with another person based on numerology numbers and relationship dynamics.',
            'report_type': 'compatibility',
            'is_premium': True,
            'is_active': True,
            'content_template': 'Compatibility report template content'
        },
        {
            'name': 'Career Guidance',
            'description': 'Explore your professional strengths, ideal career paths, and timing for career moves based on your numerology profile.',
            'report_type': 'career',
            'is_premium': True,
            'is_active': True,
            'content_template': 'Career guidance template content'
        },
        {
            'name': 'Relationship Analysis',
            'description': 'Deep dive into your relationship patterns, emotional needs, and compatibility insights.',
            'report_type': 'relationship',
            'is_premium': True,
            'is_active': True,
            'content_template': 'Relationship analysis template content'
        },
        {
            'name': 'Financial Forecast',
            'description': 'Understand your financial patterns, money mindset, and favorable periods for financial decisions.',
            'report_type': 'finance',
            'is_premium': True,
            'is_active': True,
            'content_template': 'Financial forecast template content'
        },
        {
            'name': 'Yearly Forecast',
            'description': 'Annual forecast with key themes, opportunities, and challenges for the year ahead.',
            'report_type': 'yearly',
            'is_premium': True,
            'is_active': True,
            'content_template': 'Yearly forecast template content'
        }
    ]
    
    for template_data in templates:
        ReportTemplate.objects.get_or_create(
            name=template_data['name'],
            defaults=template_data
        )

class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reporttemplate_content_template_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_report_templates),
    ]
