# Generated by Django 4.2.16 on 2026-01-09 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('numerology', '0009_breakthroughyear_crisisyear_emotionalcycle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0003_auto_20251125_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comparison_data', models.JSONField(help_text='Comparison analysis data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Report Comparison',
                'verbose_name_plural': 'Report Comparisons',
                'db_table': 'report_comparisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schedule_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('next_run_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scheduled Report',
                'verbose_name_plural': 'Scheduled Reports',
                'db_table': 'scheduled_reports',
                'ordering': ['next_run_date'],
            },
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='Whether this is a user-created template'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_report_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='template_config',
            field=models.JSONField(blank=True, default=dict, help_text='Custom section configuration for the template'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['is_custom', 'owner'], name='report_temp_is_cust_da6fed_idx'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='numerology.person'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='reports.reporttemplate'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportcomparison',
            name='report1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_report1', to='reports.generatedreport'),
        ),
        migrations.AddField(
            model_name='reportcomparison',
            name='report2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_report2', to='reports.generatedreport'),
        ),
        migrations.AddField(
            model_name='reportcomparison',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_comparisons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['user', 'is_active'], name='scheduled_r_user_id_e1b135_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['next_run_date', 'is_active'], name='scheduled_r_next_ru_4c5d74_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcomparison',
            index=models.Index(fields=['user', 'created_at'], name='report_comp_user_id_79c916_idx'),
        ),
    ]
