# Generated by Django 4.2.16 on 2025-12-15 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('specialty', models.CharField(choices=[('relationship', 'Relationship & Compatibility'), ('career', 'Career & Business'), ('spiritual', 'Spiritual Growth'), ('health', 'Health & Wellness'), ('general', 'General Numerology')], max_length=20)),
                ('experience_years', models.IntegerField()),
                ('bio', models.TextField()),
                ('application_notes', models.TextField(blank=True, help_text='Why they want to be an expert')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if rejected')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expert Application',
                'verbose_name_plural': 'Expert Applications',
                'db_table': 'expert_applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expert Availability',
                'verbose_name_plural': 'Expert Availabilities',
                'db_table': 'expert_availability',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExpertChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('blocked', 'Blocked'), ('closed', 'Closed')], default='active', max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_preview', models.CharField(blank=True, max_length=200)),
                ('unread_count_user', models.IntegerField(default=0)),
                ('unread_count_expert', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expert Chat Conversation',
                'verbose_name_plural': 'Expert Chat Conversations',
                'db_table': 'expert_chat_conversations',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('expert', 'Expert'), ('system', 'System')], max_length=10)),
                ('message_content', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('system', 'System')], default='text', max_length=10)),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='chat_files/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expert Chat Message',
                'verbose_name_plural': 'Expert Chat Messages',
                'db_table': 'expert_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertUnavailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expert Unavailability',
                'verbose_name_plural': 'Expert Unavailabilities',
                'db_table': 'expert_unavailability',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExpertVerificationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('certificate', 'Certificate'), ('license', 'License'), ('education', 'Education'), ('experience', 'Experience'), ('id_proof', 'ID Proof'), ('other', 'Other')], max_length=20)),
                ('document_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='expert_verification/%Y/%m/')),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expert Verification Document',
                'verbose_name_plural': 'Expert Verification Documents',
                'db_table': 'expert_verification_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='meeting_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='meeting_room_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='meeting_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='expert',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Linked user account if expert is a user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expert',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin comments on verification'),
        ),
        migrations.AddField(
            model_name='expert',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='expert',
            name='verification_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expert',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['payment_status'], name='consultatio_payment_e818ae_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['meeting_room_id'], name='consultatio_meeting_f5da2c_idx'),
        ),
        migrations.AddIndex(
            model_name='expert',
            index=models.Index(fields=['verification_status'], name='experts_verific_f55b03_idx'),
        ),
        migrations.AddField(
            model_name='expertverificationdocument',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='consultations.expertapplication'),
        ),
        migrations.AddField(
            model_name='expertverificationdocument',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_documents', to='consultations.expert'),
        ),
        migrations.AddField(
            model_name='expertunavailability',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailability_periods', to='consultations.expert'),
        ),
        migrations.AddField(
            model_name='expertchatmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='consultations.expertchatconversation'),
        ),
        migrations.AddField(
            model_name='expertchatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='consultations.expertchatmessage'),
        ),
        migrations.AddField(
            model_name='expertchatmessage',
            name='sender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertchatconversation',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversation', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='expertchatconversation',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chats', to='consultations.expert'),
        ),
        migrations.AddField(
            model_name='expertchatconversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertavailability',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_schedule', to='consultations.expert'),
        ),
        migrations.AddField(
            model_name='expertapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='expertverificationdocument',
            index=models.Index(fields=['expert', 'document_type'], name='expert_veri_expert__304e67_idx'),
        ),
        migrations.AddIndex(
            model_name='expertverificationdocument',
            index=models.Index(fields=['application'], name='expert_veri_applica_710274_idx'),
        ),
        migrations.AddIndex(
            model_name='expertunavailability',
            index=models.Index(fields=['expert', 'start_date', 'end_date'], name='expert_unav_expert__7d20d0_idx'),
        ),
        migrations.AddIndex(
            model_name='expertchatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='expert_chat_convers_0266a9_idx'),
        ),
        migrations.AddIndex(
            model_name='expertchatmessage',
            index=models.Index(fields=['conversation', 'is_read'], name='expert_chat_convers_1d4391_idx'),
        ),
        migrations.AddIndex(
            model_name='expertchatmessage',
            index=models.Index(fields=['sender_user', 'created_at'], name='expert_chat_sender__9a9089_idx'),
        ),
        migrations.AddIndex(
            model_name='expertchatconversation',
            index=models.Index(fields=['user', 'expert', 'status'], name='expert_chat_user_id_5d3b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='expertchatconversation',
            index=models.Index(fields=['expert', 'status'], name='expert_chat_expert__bef85a_idx'),
        ),
        migrations.AddIndex(
            model_name='expertchatconversation',
            index=models.Index(fields=['user', 'status'], name='expert_chat_user_id_ab5ecb_idx'),
        ),
        migrations.AddConstraint(
            model_name='expertchatconversation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user', 'expert'), name='unique_active_conversation'),
        ),
        migrations.AddIndex(
            model_name='expertavailability',
            index=models.Index(fields=['expert', 'day_of_week'], name='expert_avai_expert__6ec7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='expertavailability',
            index=models.Index(fields=['expert', 'is_available'], name='expert_avai_expert__4aca5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expertavailability',
            unique_together={('expert', 'day_of_week', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='expertapplication',
            index=models.Index(fields=['user', 'status'], name='expert_appl_user_id_903bfe_idx'),
        ),
        migrations.AddIndex(
            model_name='expertapplication',
            index=models.Index(fields=['status'], name='expert_appl_status_0a5133_idx'),
        ),
    ]
