name: numerai
region: nyc

ingress:
  rules:
    - match:
        path:
          prefix: /api
      component:
        name: backend
    - match:
        path:
          prefix: /admin
      component:
        name: backend
    - match:
        path:
          prefix: /static
      component:
        name: backend
    - match:
        path:
          prefix: /media
      component:
        name: backend

services:
  # Django Backend Service
  - name: backend
    github:
      repo: theburhanahmed/NumerAI
      branch: main
      deploy_on_push: true
    source_dir: backend
    build_command: pip install -r requirements.txt
    run_command: ./start.sh
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8000
    health_check:
      http_path: /api/v1/health/
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: DJANGO_SETTINGS_MODULE
        value: numerai.settings.production
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ALLOWED_HOSTS
        scope: RUN_TIME
        type: SECRET
      - key: DB_NAME
        value: numerai
      - key: DB_USER
        value: numerai
      - key: DB_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: DB_HOST
        value: postgres
      - key: DB_PORT
        value: "5432"
      - key: REDIS_URL
        value: redis://redis:6379/0
      - key: CELERY_BROKER_URL
        value: redis://redis:6379/1
      - key: CELERY_RESULT_BACKEND
        value: redis://redis:6379/2
      - key: CORS_ALLOWED_ORIGINS
        scope: RUN_TIME
        type: SECRET
      - key: CSRF_TRUSTED_ORIGINS
        scope: RUN_TIME
        type: SECRET
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        scope: RUN_TIME
        type: SECRET
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_USER
        scope: RUN_TIME
        type: SECRET
      - key: EMAIL_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: DEFAULT_FROM_EMAIL
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_PUBLIC_KEY
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_WEBHOOK_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: FIREBASE_CREDENTIALS
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: APPLE_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: APPLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: APPLE_KEY_ID
        scope: RUN_TIME
        type: SECRET
      - key: APPLE_TEAM_ID
        scope: RUN_TIME
        type: SECRET

  # Next.js Frontend Service
  - name: frontend
    github:
      repo: theburhanahmed/NumerAI
      branch: main
      deploy_on_push: true
    source_dir: frontend
    build_command: npm ci --include=dev || npm install && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    health_check:
      http_path: /
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        scope: RUN_TIME
        type: SECRET
      - key: PORT
        value: "3000"

workers:
  # PostgreSQL Database Container Service
  - name: postgres
    image:
      registry_type: DOCKER_HUB
      repository: postgres
      tag: "14-alpine"
    instance_count: 1
    instance_size_slug: basic-xxs
    run_command: postgres -c max_connections=100
    envs:
      - key: POSTGRES_DB
        value: numerai
      - key: POSTGRES_USER
        value: numerai
      - key: POSTGRES_PASSWORD
        scope: RUN_TIME
        type: SECRET

  # Redis Container Service
  - name: redis
    image:
      registry_type: DOCKER_HUB
      repository: redis
      tag: "7-alpine"
    instance_count: 1
    instance_size_slug: basic-xxs
    run_command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  # Celery Worker Service
  - name: celery-worker
    github:
      repo: theburhanahmed/NumerAI
      branch: main
      deploy_on_push: true
    source_dir: backend
    build_command: pip install -r requirements.txt
    run_command: celery -A numerai worker -l info
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DJANGO_SETTINGS_MODULE
        value: numerai.settings.production
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ALLOWED_HOSTS
        scope: RUN_TIME
        type: SECRET
      - key: DB_NAME
        value: numerai
      - key: DB_USER
        value: numerai
      - key: DB_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: DB_HOST
        value: postgres
      - key: DB_PORT
        value: "5432"
      - key: REDIS_URL
        value: redis://redis:6379/0
      - key: CELERY_BROKER_URL
        value: redis://redis:6379/1
      - key: CELERY_RESULT_BACKEND
        value: redis://redis:6379/2
      - key: CORS_ALLOWED_ORIGINS
        scope: RUN_TIME
        type: SECRET
      - key: CSRF_TRUSTED_ORIGINS
        scope: RUN_TIME
        type: SECRET
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        scope: RUN_TIME
        type: SECRET
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_USER
        scope: RUN_TIME
        type: SECRET
      - key: EMAIL_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: DEFAULT_FROM_EMAIL
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_PUBLIC_KEY
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_WEBHOOK_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: FIREBASE_CREDENTIALS
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: APPLE_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: APPLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: APPLE_KEY_ID
        scope: RUN_TIME
        type: SECRET
      - key: APPLE_TEAM_ID
        scope: RUN_TIME
        type: SECRET

  # Celery Beat Service
  - name: celery-beat
    github:
      repo: theburhanahmed/NumerAI
      branch: main
      deploy_on_push: true
    source_dir: backend
    build_command: pip install -r requirements.txt
    run_command: celery -A numerai beat -l info
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DJANGO_SETTINGS_MODULE
        value: numerai.settings.production
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ALLOWED_HOSTS
        scope: RUN_TIME
        type: SECRET
      - key: DB_NAME
        value: numerai
      - key: DB_USER
        value: numerai
      - key: DB_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: DB_HOST
        value: postgres
      - key: DB_PORT
        value: "5432"
      - key: REDIS_URL
        value: redis://redis:6379/0
      - key: CELERY_BROKER_URL
        value: redis://redis:6379/1
      - key: CELERY_RESULT_BACKEND
        value: redis://redis:6379/2
      - key: CORS_ALLOWED_ORIGINS
        scope: RUN_TIME
        type: SECRET
      - key: CSRF_TRUSTED_ORIGINS
        scope: RUN_TIME
        type: SECRET
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        scope: RUN_TIME
        type: SECRET
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_USER
        scope: RUN_TIME
        type: SECRET
      - key: EMAIL_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: DEFAULT_FROM_EMAIL
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_PUBLIC_KEY
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: STRIPE_WEBHOOK_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: FIREBASE_CREDENTIALS
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: APPLE_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: APPLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: APPLE_KEY_ID
        scope: RUN_TIME
        type: SECRET
      - key: APPLE_TEAM_ID
        scope: RUN_TIME
        type: SECRET
