# Generated by Django 4.2.16 on 2025-11-30 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_life_paths', models.JSONField(blank=True, default=list)),
                ('min_compatibility_score', models.IntegerField(default=70)),
                ('age_range_min', models.IntegerField(blank=True, null=True)),
                ('age_range_max', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_preferences',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.IntegerField()),
                ('match_details', models.JSONField(default=dict)),
                ('is_mutual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_initiated', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['-match_score'],
                'indexes': [models.Index(fields=['user1', 'match_score'], name='matches_user1_i_3881ce_idx'), models.Index(fields=['user2', 'match_score'], name='matches_user2_i_e795eb_idx')],
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
