web: gunicorn --bind 0.0.0.0:$PORT --workers 4 --threads 2 --timeout 120 --access-logfile - --error-logfile - numerai.wsgi:application
worker: celery -A numerai worker --loglevel=info --concurrency=2
beat: celery -A numerai beat --loglevel=info
