# Generated by Django 4.2.16 on 2025-12-15 19:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('numerology', '0006_phonereport_detailedreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('person', 'Person'), ('asset', 'Asset'), ('event', 'Event')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, help_text='Required for person, optional for event', null=True)),
                ('relationship_type', models.CharField(blank=True, choices=[('family', 'Family'), ('friend', 'Friend'), ('partner', 'Romantic Partner'), ('colleague', 'Colleague'), ('business_partner', 'Business Partner'), ('child', 'Child'), ('client', 'Client'), ('other', 'Other')], max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible storage for entity-specific data')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numerology_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_profiles', to='numerology.numerologyprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entity Profile',
                'verbose_name_plural': 'Entity Profiles',
                'db_table': 'entity_profiles',
            },
        ),
        migrations.CreateModel(
            name='EntityInfluence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('influence_strength', models.IntegerField(help_text='Influence strength 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('impact_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=20)),
                ('impact_areas', models.JSONField(default=dict, help_text='Impact areas: health, money, career, relationships, stability')),
                ('cycle_period', models.CharField(choices=[('year', 'Year'), ('month', 'Month')], max_length=10)),
                ('cycle_value', models.CharField(help_text="'2026' or '2026-04'", max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influences', to='meus.entityprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_influences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entity Influence',
                'verbose_name_plural': 'Entity Influences',
                'db_table': 'entity_influences',
            },
        ),
        migrations.CreateModel(
            name='CrossProfileAnalysisCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_combination_hash', models.CharField(db_index=True, help_text='SHA-256 hash of sorted entity IDs', max_length=64)),
                ('analysis_result', models.JSONField(help_text='Cached analysis result')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Cache expiration time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cross Profile Analysis Cache',
                'verbose_name_plural': 'Cross Profile Analysis Cache',
                'db_table': 'cross_profile_analysis_cache',
            },
        ),
        migrations.CreateModel(
            name='AssetProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('property', 'Property'), ('business', 'Business'), ('phone', 'Phone')], max_length=20)),
                ('asset_number', models.CharField(help_text='License plate, house number, phone number, etc.', max_length=100)),
                ('numerology_vibration', models.IntegerField(blank=True, help_text='Calculated vibration number', null=True)),
                ('safety_score', models.IntegerField(blank=True, help_text='Safety score for vehicles (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('compatibility_with_owner', models.IntegerField(blank=True, help_text='Compatibility with owner (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Asset-specific data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.OneToOneField(help_text='Must be an asset type entity', on_delete=django.db.models.deletion.CASCADE, related_name='asset_profile', to='meus.entityprofile')),
            ],
            options={
                'verbose_name': 'Asset Profile',
                'verbose_name_plural': 'Asset Profiles',
                'db_table': 'asset_profiles',
            },
        ),
        migrations.CreateModel(
            name='UniverseEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('business_launch', 'Business Launch'), ('travel', 'Travel'), ('purchase', 'Purchase'), ('medical', 'Medical Procedure'), ('decision', 'Big Decision'), ('other', 'Other')], max_length=50)),
                ('event_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('numerology_insight', models.JSONField(blank=True, default=dict, help_text='Numerology analysis of the event date')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_entities', models.ManyToManyField(blank=True, related_name='events', to='meus.entityprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universe_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Universe Event',
                'verbose_name_plural': 'Universe Events',
                'db_table': 'universe_events',
                'indexes': [models.Index(fields=['user'], name='universe_ev_user_id_4357c5_idx'), models.Index(fields=['event_date'], name='universe_ev_event_d_f4fe7f_idx'), models.Index(fields=['event_type'], name='universe_ev_event_t_986173_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntityRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(blank=True, choices=[('compatible', 'Compatible'), ('challenging', 'Challenging'), ('neutral', 'Neutral'), ('conflict', 'Conflict'), ('harmony', 'Harmony')], max_length=50, null=True)),
                ('compatibility_score', models.IntegerField(blank=True, help_text='Compatibility score 0-100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('influence_score', models.IntegerField(blank=True, help_text='Influence score -100 to 100', null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)])),
                ('analysis_data', models.JSONField(blank=True, default=dict, help_text='Detailed compatibility analysis')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='For cache invalidation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_entity_1', to='meus.entityprofile')),
                ('entity_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_entity_2', to='meus.entityprofile')),
            ],
            options={
                'verbose_name': 'Entity Relationship',
                'verbose_name_plural': 'Entity Relationships',
                'db_table': 'entity_relationships',
                'indexes': [models.Index(fields=['entity_1'], name='entity_rela_entity__10a166_idx'), models.Index(fields=['entity_2'], name='entity_rela_entity__fe9aae_idx'), models.Index(fields=['compatibility_score'], name='entity_rela_compati_6ef36f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='entityrelationship',
            constraint=models.CheckConstraint(check=models.Q(('entity_1', models.F('entity_2')), _negated=True), name='different_entities'),
        ),
        migrations.AlterUniqueTogether(
            name='entityrelationship',
            unique_together={('entity_1', 'entity_2')},
        ),
        migrations.AddIndex(
            model_name='entityprofile',
            index=models.Index(fields=['user', 'is_active'], name='entity_prof_user_id_8fc23d_idx'),
        ),
        migrations.AddIndex(
            model_name='entityprofile',
            index=models.Index(fields=['entity_type'], name='entity_prof_entity__2ad6a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='entityprofile',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('date_of_birth__isnull', False), ('entity_type', 'person')), ('entity_type__in', ['asset', 'event']), _connector='OR'), name='valid_person_dob'),
        ),
        migrations.AddIndex(
            model_name='entityinfluence',
            index=models.Index(fields=['user'], name='entity_infl_user_id_a038e9_idx'),
        ),
        migrations.AddIndex(
            model_name='entityinfluence',
            index=models.Index(fields=['entity'], name='entity_infl_entity__2c0e58_idx'),
        ),
        migrations.AddIndex(
            model_name='entityinfluence',
            index=models.Index(fields=['cycle_period', 'cycle_value'], name='entity_infl_cycle_p_46d571_idx'),
        ),
        migrations.AddIndex(
            model_name='entityinfluence',
            index=models.Index(fields=['impact_type'], name='entity_infl_impact__6d80a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entityinfluence',
            unique_together={('user', 'entity', 'cycle_period', 'cycle_value')},
        ),
        migrations.AddIndex(
            model_name='crossprofileanalysiscache',
            index=models.Index(fields=['user'], name='cross_profi_user_id_cea76a_idx'),
        ),
        migrations.AddIndex(
            model_name='crossprofileanalysiscache',
            index=models.Index(fields=['expires_at'], name='cross_profi_expires_e25fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='crossprofileanalysiscache',
            index=models.Index(fields=['entity_combination_hash'], name='cross_profi_entity__8c30c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='crossprofileanalysiscache',
            unique_together={('user', 'entity_combination_hash')},
        ),
        migrations.AddIndex(
            model_name='assetprofile',
            index=models.Index(fields=['entity'], name='asset_profi_entity__ab08e5_idx'),
        ),
        migrations.AddIndex(
            model_name='assetprofile',
            index=models.Index(fields=['asset_type'], name='asset_profi_asset_t_f51f6e_idx'),
        ),
    ]
