# Generated by Django 4.2.16 on 2025-12-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='entityprofile',
            name='valid_person_dob',
        ),
        migrations.AddConstraint(
            model_name='entityprofile',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('date_of_birth__isnull', False), ('entity_type', 'person')), models.Q(('date_of_birth__isnull', True), ('entity_type__in', ['asset', 'event'])), models.Q(('date_of_birth__isnull', False), ('entity_type__in', ['asset', 'event'])), _connector='OR'), name='valid_person_dob'),
        ),
    ]
