# Generated by Django 4.2.16 on 2026-07-28 02:17

from django.db import migrations, models


NUMBER_FIELDS = (
    'life_path_number', 'destiny_number', 'soul_urge_number', 'personality_number',
    'attitude_number', 'maturity_number', 'balance_number', 'personal_year_number',
    'personal_month_number', 'birthday_number', 'driver_number', 'conductor_number',
)


def copy_entity_numerology(apps, schema_editor):
    EntityProfile = apps.get_model('meus', 'EntityProfile')
    for entity in EntityProfile.objects.exclude(numerology_profile__isnull=True).select_related('numerology_profile'):
        profile = entity.numerology_profile
        entity.numerology_data = {
            field: getattr(profile, field)
            for field in NUMBER_FIELDS
            if getattr(profile, field, None) is not None
        }
        entity.save(update_fields=['numerology_data'])


class Migration(migrations.Migration):

    dependencies = [
        ('meus', '0002_remove_entityprofile_valid_person_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityprofile',
            name='numerology_data',
            field=models.JSONField(blank=True, default=dict, help_text='Independent calculated numerology data for this entity'),
        ),
        migrations.RunPython(copy_entity_numerology, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='entityprofile',
            name='numerology_profile',
        ),
    ]
