# Generated by Django 4.2.16 on 2025-11-30 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('feature_used', 'Feature Used'), ('page_viewed', 'Page Viewed'), ('calculation_performed', 'Calculation Performed'), ('report_generated', 'Report Generated'), ('reminder_set', 'Reminder Set'), ('decision_made', 'Decision Made'), ('insight_viewed', 'Insight Viewed')], max_length=50)),
                ('action_details', models.JSONField(blank=True, default=dict)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Behavior',
                'verbose_name_plural': 'User Behaviors',
                'db_table': 'user_behaviors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='user_behavi_user_id_9bb153_idx'), models.Index(fields=['user', 'action_type'], name='user_behavi_user_id_b8ddf0_idx'), models.Index(fields=['action_type', 'created_at'], name='user_behavi_action__0a0dd4_idx')],
            },
        ),
        migrations.CreateModel(
            name='GrowthMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('feature_adoption', 'Feature Adoption'), ('engagement_score', 'Engagement Score'), ('accuracy_tracking', 'Accuracy Tracking'), ('consistency', 'Consistency')], max_length=50)),
                ('metric_value', models.FloatField()),
                ('metric_data', models.JSONField(blank=True, default=dict)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Growth Metric',
                'verbose_name_plural': 'Growth Metrics',
                'db_table': 'growth_metrics',
                'ordering': ['-period_end', '-created_at'],
                'indexes': [models.Index(fields=['user', 'metric_type'], name='growth_metr_user_id_df38e5_idx'), models.Index(fields=['user', 'period_end'], name='growth_metr_user_id_fb851b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('engagement', 'Engagement'), ('usage_pattern', 'Usage Pattern'), ('growth', 'Growth'), ('recommendation', 'Recommendation')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('insight_data', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.FloatField(default=0.5)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics Insight',
                'verbose_name_plural': 'Analytics Insights',
                'db_table': 'analytics_insights',
                'ordering': ['-confidence_score', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='analytics_i_user_id_17c757_idx'), models.Index(fields=['user', 'insight_type'], name='analytics_i_user_id_90161e_idx')],
            },
        ),
    ]
