# Generated by Django 4.2.16 on 2025-12-22 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('variants', models.JSONField(default=list)),
                ('target_audience', models.JSONField(default=dict)),
                ('primary_metric', models.CharField(max_length=100)),
                ('secondary_metrics', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'A/B Test',
                'verbose_name_plural': 'A/B Tests',
                'db_table': 'ab_tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(db_index=True, max_length=100)),
                ('metric_category', models.CharField(db_index=True, max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('value_type', models.CharField(max_length=20)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField(db_index=True)),
                ('period_type', models.CharField(max_length=20)),
                ('dimensions', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Business Metric',
                'verbose_name_plural': 'Business Metrics',
                'db_table': 'business_metrics',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='ConversionFunnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('steps', models.JSONField(default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('time_window_hours', models.IntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversion Funnel',
                'verbose_name_plural': 'Conversion Funnels',
                'db_table': 'conversion_funnels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(db_index=True, max_length=100)),
                ('event_category', models.CharField(db_index=True, max_length=50)),
                ('event_properties', models.JSONField(blank=True, default=dict)),
                ('funnel_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('funnel_step', models.CharField(blank=True, max_length=50)),
                ('funnel_position', models.IntegerField(blank=True, null=True)),
                ('experiment_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('variant_id', models.CharField(blank=True, max_length=100)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('page_path', models.CharField(blank=True, max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_trackings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Tracking',
                'verbose_name_plural': 'Event Trackings',
                'db_table': 'event_tracking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(db_index=True, max_length=50)),
                ('activity_data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('page_path', models.CharField(blank=True, max_length=500)),
                ('feature_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'db_table': 'user_activity_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserJourney',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('journey_type', models.CharField(db_index=True, max_length=50)),
                ('steps', models.JSONField(default=list)),
                ('current_step', models.CharField(blank=True, max_length=100)),
                ('completed', models.BooleanField(default=False)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('steps_completed', models.IntegerField(default=0)),
                ('total_steps', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Journey',
                'verbose_name_plural': 'User Journeys',
                'db_table': 'user_journey',
                'ordering': ['-started_at'],
            },
        ),
        migrations.RemoveField(
            model_name='growthmetric',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userbehavior',
            name='user',
        ),
        migrations.DeleteModel(
            name='AnalyticsInsight',
        ),
        migrations.DeleteModel(
            name='GrowthMetric',
        ),
        migrations.DeleteModel(
            name='UserBehavior',
        ),
        migrations.AddIndex(
            model_name='businessmetric',
            index=models.Index(fields=['metric_name', 'period_start'], name='business_me_metric__50cad7_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmetric',
            index=models.Index(fields=['metric_category', 'period_start'], name='business_me_metric__a49a39_idx'),
        ),
        migrations.AddIndex(
            model_name='businessmetric',
            index=models.Index(fields=['period_type', 'period_start'], name='business_me_period__9ac94d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='businessmetric',
            unique_together={('metric_name', 'period_start', 'period_type')},
        ),
        migrations.AddIndex(
            model_name='userjourney',
            index=models.Index(fields=['user', 'journey_type', 'started_at'], name='user_journe_user_id_1ade6a_idx'),
        ),
        migrations.AddIndex(
            model_name='userjourney',
            index=models.Index(fields=['session_id', 'started_at'], name='user_journe_session_15c54b_idx'),
        ),
        migrations.AddIndex(
            model_name='userjourney',
            index=models.Index(fields=['completed', 'started_at'], name='user_journe_complet_05aee8_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', 'created_at'], name='user_activi_user_id_fe3755_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['activity_type', 'created_at'], name='user_activi_activit_5f49e2_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['session_id', 'created_at'], name='user_activi_session_014988_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['feature_name', 'created_at'], name='user_activi_feature_168387_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtracking',
            index=models.Index(fields=['user', 'event_name', 'created_at'], name='event_track_user_id_22197d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtracking',
            index=models.Index(fields=['funnel_name', 'funnel_position'], name='event_track_funnel__6f3ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtracking',
            index=models.Index(fields=['experiment_id', 'variant_id'], name='event_track_experim_724764_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtracking',
            index=models.Index(fields=['event_category', 'created_at'], name='event_track_event_c_77f07c_idx'),
        ),
    ]
