# Generated by Django 4.2.16 on 2025-11-30 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_text', models.TextField()),
                ('decision_category', models.CharField(choices=[('career', 'Career'), ('relationship', 'Relationship'), ('financial', 'Financial'), ('health', 'Health'), ('education', 'Education'), ('travel', 'Travel'), ('business', 'Business'), ('personal', 'Personal'), ('other', 'Other')], default='personal', max_length=50)),
                ('decision_date', models.DateField()),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('personal_day_number', models.IntegerField()),
                ('personal_year_number', models.IntegerField()),
                ('personal_month_number', models.IntegerField()),
                ('timing_score', models.IntegerField()),
                ('timing_reasoning', models.JSONField(default=list)),
                ('recommendation', models.TextField()),
                ('suggested_actions', models.JSONField(default=list)),
                ('is_made', models.BooleanField(default=False)),
                ('made_date', models.DateField(blank=True, null=True)),
                ('outcome_recorded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Decision',
                'verbose_name_plural': 'Decisions',
                'db_table': 'decisions',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='DecisionOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome_type', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('pending', 'Pending')], max_length=20)),
                ('outcome_description', models.TextField()),
                ('satisfaction_score', models.IntegerField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='decisions.decision')),
            ],
            options={
                'verbose_name': 'Decision Outcome',
                'verbose_name_plural': 'Decision Outcomes',
                'db_table': 'decision_outcomes',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_type', models.CharField(max_length=100)),
                ('pattern_data', models.JSONField()),
                ('confidence_score', models.FloatField(default=0.5)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Decision Pattern',
                'verbose_name_plural': 'Decision Patterns',
                'db_table': 'decision_patterns',
                'ordering': ['-confidence_score', '-discovered_at'],
                'indexes': [models.Index(fields=['user', 'pattern_type'], name='decision_pa_user_id_6e8d98_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['user', 'decision_date'], name='decisions_user_id_a00fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['user', 'is_made'], name='decisions_user_id_33c750_idx'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['decision_category'], name='decisions_decisio_9ce31d_idx'),
        ),
    ]
