# Generated by Django 4.2.16 on 2025-12-15 19:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Unique identifier for the feature flag', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Feature description')),
                ('category', models.CharField(choices=[('core', 'Core Features'), ('meus', 'MEUS (Multi-Entity Universe System)'), ('numerology', 'Numerology Features'), ('ai', 'AI Features'), ('reports', 'Reports'), ('social', 'Social Features'), ('premium', 'Premium Features')], default='core', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Global enable/disable for the feature')),
                ('default_tier', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('elite', 'Elite')], default='free', help_text='Minimum tier required by default', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'db_table': 'feature_flags',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionFeatureAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('elite', 'Elite')], db_index=True, max_length=20)),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether this tier has access to the feature')),
                ('limits', models.JSONField(blank=True, default=dict, help_text='Usage limits (e.g., max_entities, max_reports)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_access', to='feature_flags.featureflag')),
            ],
            options={
                'verbose_name': 'Subscription Feature Access',
                'verbose_name_plural': 'Subscription Feature Access',
                'db_table': 'subscription_feature_access',
                'indexes': [models.Index(fields=['subscription_tier', 'is_enabled'], name='subscriptio_subscri_d4d5a1_idx')],
                'unique_together': {('subscription_tier', 'feature_flag')},
            },
        ),
    ]
