# Generated by Django 4.2.16 on 2026-07-28 01:30

from django.db import migrations


FEATURES = [
    ('birth_date_numerology', 'Birth Date Numerology', 'core', 'free'),
    ('basic_interpretations', 'Basic Interpretations', 'core', 'free'),
    ('ai_chat', 'AI Numerology Chat', 'ai', 'free'),
    ('reports_basic', 'Basic Reports', 'reports', 'free'),
    ('social_connections', 'Social Connections', 'social', 'free'),
    ('name_numerology', 'Name Numerology', 'core', 'basic'),
    ('lo_shu_grid', 'Lo Shu Grid', 'core', 'basic'),
    ('rectification_suggestions', 'Rectification Suggestions', 'core', 'basic'),
    ('phone_numerology', 'Phone Number Numerology', 'core', 'premium'),
    ('detailed_analysis', 'Detailed Analysis', 'core', 'premium'),
    ('compatibility_insights', 'Compatibility Insights', 'core', 'premium'),
    ('numerology_compatibility', 'Enhanced Compatibility', 'numerology', 'premium'),
    ('numerology_phone', 'Advanced Phone Numerology', 'numerology', 'premium'),
    ('numerology_relationships', 'Relationship Numerology', 'numerology', 'premium'),
    ('numerology_timing', 'Timing Numerology', 'numerology', 'premium'),
    ('numerology_visualizations', 'Numerology Visualizations', 'numerology', 'premium'),
    ('meus_entities', 'MEUS Entity Management', 'meus', 'premium'),
    ('meus_assets', 'MEUS Asset Numerology', 'meus', 'premium'),
    ('meus_events', 'MEUS Event Tracking', 'meus', 'premium'),
    ('meus_analysis', 'MEUS Cross-Entity Analysis', 'meus', 'premium'),
    ('meus_dashboard', 'MEUS Universe Dashboard', 'meus', 'premium'),
    ('numerology_essence_cycles', 'Essence Cycles', 'numerology', 'premium'),
    ('numerology_cycle_visualization', 'Cycle Visualization', 'numerology', 'premium'),
    ('numerology_universal_cycles', 'Universal Cycles', 'numerology', 'premium'),
    ('numerology_cycle_alerts', 'Cycle Alerts', 'numerology', 'premium'),
    ('numerology_vehicle', 'Vehicle Numerology', 'numerology', 'premium'),
    ('numerology_property', 'Property Numerology', 'numerology', 'premium'),
    ('numerology_business', 'Business Numerology', 'numerology', 'premium'),
    ('numerology_sexual_energy', 'Sexual Energy Numerology', 'numerology', 'premium'),
    ('numerology_marriage_harmony', 'Marriage Harmony Cycles', 'numerology', 'premium'),
    ('numerology_multi_partner', 'Multi-Partner Comparison', 'numerology', 'premium'),
    ('numerology_timing_optimization', 'Timing Optimization', 'numerology', 'premium'),
    ('numerology_danger_dates', 'Danger Dates Identification', 'numerology', 'premium'),
    ('numerology_lo_shu_visualization', 'Lo Shu Grid Visualization', 'numerology', 'premium'),
    ('numerology_grid_comparison', 'Grid Comparison', 'numerology', 'premium'),
    ('ai_co_pilot', 'AI Co-Pilot', 'ai', 'premium'),
    ('ai_decision_engine', 'Decision Engine', 'ai', 'premium'),
    ('reports_detailed', 'Detailed Reports', 'reports', 'premium'),
    ('reports_pdf_export', 'PDF Export', 'reports', 'premium'),
    ('social_matchmaking', 'Matchmaking', 'social', 'premium'),
    ('raj_yog_analysis', 'Raj Yog Analysis', 'core', 'elite'),
    ('yearly_forecast', 'Yearly Forecast', 'core', 'elite'),
    ('expert_recommendations', 'Expert Recommendations', 'core', 'elite'),
    ('meus_recommendations', 'MEUS Action Recommendations', 'meus', 'elite'),
    ('meus_reports', 'MEUS Multi-Profile Reports', 'meus', 'elite'),
    ('numerology_health', 'Health Numerology', 'numerology', 'elite'),
    ('numerology_medical_timing', 'Medical Procedure Timing', 'numerology', 'elite'),
    ('numerology_name_correction', 'Name Correction', 'numerology', 'elite'),
    ('numerology_phonetic_optimization', 'Phonetic Optimization', 'numerology', 'elite'),
    ('numerology_spiritual', 'Spiritual Numerology', 'numerology', 'elite'),
    ('numerology_soul_contracts', 'Soul Contracts', 'numerology', 'elite'),
    ('numerology_predictive', 'Predictive Numerology', 'numerology', 'elite'),
    ('numerology_forecasting', 'Life Forecasting', 'numerology', 'elite'),
    ('numerology_generational', 'Generational Numerology', 'numerology', 'elite'),
    ('numerology_family_analysis', 'Family Analysis', 'numerology', 'elite'),
    ('numerology_feng_shui', 'Feng Shui Hybrid', 'numerology', 'elite'),
    ('numerology_space_optimization', 'Space Optimization', 'numerology', 'elite'),
    ('numerology_mental_state', 'Mental State AI', 'numerology', 'elite'),
    ('numerology_emotional_tracking', 'Emotional Tracking', 'numerology', 'elite'),
    ('ai_life_coach', 'Numerology Life Coach', 'ai', 'elite'),
    ('reports_bulk', 'Bulk Report Generation', 'reports', 'elite'),
]
TIERS = ('free', 'basic', 'premium', 'elite')


def seed_entitlement_matrix(apps, schema_editor):
    FeatureFlag = apps.get_model('feature_flags', 'FeatureFlag')
    SubscriptionFeatureAccess = apps.get_model('feature_flags', 'SubscriptionFeatureAccess')
    for name, display_name, category, minimum_tier in FEATURES:
        flag, _ = FeatureFlag.objects.update_or_create(
            name=name,
            defaults={
                'display_name': display_name,
                'category': category,
                'default_tier': minimum_tier,
                'is_active': True,
            },
        )
        minimum_index = TIERS.index(minimum_tier)
        for index, tier in enumerate(TIERS):
            SubscriptionFeatureAccess.objects.update_or_create(
                feature_flag=flag,
                subscription_tier=tier,
                defaults={'is_enabled': index >= minimum_index},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_entitlement_matrix, migrations.RunPython.noop),
    ]
