# Generated by Django 4.2.16 on 2025-11-30 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('birth_chart_viewed', 'Birth Chart Viewed'), ('daily_reading_viewed', 'Daily Reading Viewed'), ('compatibility_checked', 'Compatibility Checked'), ('remedy_tracked', 'Remedy Tracked'), ('ai_chat_used', 'AI Chat Used'), ('report_generated', 'Report Generated'), ('profile_updated', 'Profile Updated'), ('person_added', 'Person Added'), ('consultation_booked', 'Consultation Booked')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='user_activi_user_id_c742e0_idx'), models.Index(fields=['user', 'activity_type'], name='user_activi_user_id_290628_idx'), models.Index(fields=['activity_type', 'created_at'], name='user_activi_activit_1c12f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuickInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('daily_tip', 'Daily Tip'), ('cycle_reminder', 'Cycle Reminder'), ('pattern_discovery', 'Pattern Discovery'), ('recommendation', 'Recommendation'), ('alert', 'Alert')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('action_text', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('is_read', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quick Insight',
                'verbose_name_plural': 'Quick Insights',
                'db_table': 'quick_insights',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='quick_insig_user_id_f34539_idx'), models.Index(fields=['user', 'expires_at'], name='quick_insig_user_id_ac26e9_idx'), models.Index(fields=['insight_type', 'created_at'], name='quick_insig_insight_8f19e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_type', models.CharField(choices=[('daily_reading', 'Daily Reading'), ('birth_chart', 'Birth Chart'), ('calendar', 'Calendar'), ('co_pilot', 'AI Co-Pilot'), ('insights', 'Insights'), ('activity', 'Activity Feed'), ('quick_actions', 'Quick Actions'), ('remedies', 'Remedies'), ('compatibility', 'Compatibility'), ('analytics', 'Analytics')], max_length=50)),
                ('position', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'db_table': 'dashboard_widgets',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['user', 'position'], name='dashboard_w_user_id_5fc0c4_idx'), models.Index(fields=['user', 'is_visible'], name='dashboard_w_user_id_60cb5b_idx')],
                'unique_together': {('user', 'widget_type')},
            },
        ),
    ]
