# Generated by Django 4.2.16 on 2026-07-28 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('elite', 'Elite')], max_length=20)),
                ('to_plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('elite', 'Elite')], max_length=20)),
                ('status', models.CharField(choices=[('pending_checkout', 'Pending Checkout'), ('pending_period_end', 'Pending Period End'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], max_length=30)),
                ('change_type', models.CharField(choices=[('checkout', 'Checkout'), ('upgrade', 'Upgrade'), ('downgrade', 'Downgrade'), ('cancel', 'Cancel'), ('sync', 'Synchronization')], max_length=20)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='admin', max_length=30)),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('stripe_schedule_id', models.CharField(blank=True, max_length=255, null=True)),
                ('checkout_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_subscription_changes', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='payments.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscription_changes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_e98038_idx'), models.Index(fields=['status', 'effective_at'], name='subscriptio_status_cef225_idx')],
            },
        ),
    ]
