# Generated by Django 4.2.16 on 2025-11-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numerology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerologyprofile',
            name='lo_shu_grid',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
