# Generated by Django 4.2.16 on 2025-12-01 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('numerology', '0002_numerologyprofile_lo_shu_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreading',
            name='llm_explanation',
            field=models.TextField(blank=True, help_text='LLM-generated personalized explanation', null=True),
        ),
        migrations.AddField(
            model_name='dailyreading',
            name='raj_yog_insight',
            field=models.TextField(blank=True, help_text='Raj Yog insight for this day', null=True),
        ),
        migrations.AddField(
            model_name='dailyreading',
            name='raj_yog_status',
            field=models.CharField(blank=True, help_text='Raj Yog status for this day', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('explanation_type', models.CharField(choices=[('raj_yog', 'Raj Yog Explanation'), ('daily', 'Daily Reading Explanation'), ('weekly', 'Weekly Report Explanation'), ('yearly', 'Yearly Report Explanation'), ('number', 'Number Interpretation'), ('general', 'General Numerology Insight')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('llm_provider', models.CharField(blank=True, help_text='OpenAI, Anthropic, etc.', max_length=50, null=True)),
                ('llm_model', models.CharField(blank=True, max_length=100, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('context_data', models.JSONField(default=dict, help_text='Numerology data used to generate explanation')),
                ('is_cached', models.BooleanField(default=False)),
                ('cache_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('embedding', models.JSONField(blank=True, help_text='Vector embedding for semantic search', null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Explanation',
                'verbose_name_plural': 'Explanations',
                'db_table': 'explanations',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='dailyreading',
            name='explanation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_readings', to='numerology.explanation'),
        ),
        migrations.CreateModel(
            name='RajYogDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_detected', models.BooleanField(default=False)),
                ('yog_type', models.CharField(blank=True, choices=[('leadership', 'Leadership Raj Yog'), ('spiritual', 'Spiritual Raj Yog'), ('material', 'Material Raj Yog'), ('creative', 'Creative Raj Yog'), ('service', 'Service Raj Yog'), ('master', 'Master Number Raj Yog'), ('other', 'Other Raj Yog')], max_length=20, null=True)),
                ('yog_name', models.CharField(blank=True, max_length=200, null=True)),
                ('strength_score', models.IntegerField(default=0, help_text='Raj Yog strength score (0-100)')),
                ('contributing_numbers', models.JSONField(default=dict, help_text='Numbers that contributed to Raj Yog detection')),
                ('detected_combinations', models.JSONField(default=list, help_text='List of detected number combinations')),
                ('calculation_system', models.CharField(choices=[('pythagorean', 'Pythagorean'), ('chaldean', 'Chaldean')], default='pythagorean', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raj_yog_detections', to='numerology.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raj_yog_detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Raj Yog Detection',
                'verbose_name_plural': 'Raj Yog Detections',
                'db_table': 'raj_yog_detections',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['user', 'is_detected'], name='raj_yog_det_user_id_f6c749_idx'), models.Index(fields=['person', 'is_detected'], name='raj_yog_det_person__f2b261_idx'), models.Index(fields=['yog_type'], name='raj_yog_det_yog_typ_3152a5_idx'), models.Index(fields=['strength_score'], name='raj_yog_det_strengt_995ddf_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='explanation',
            index=models.Index(fields=['user', 'explanation_type'], name='explanation_user_id_16c16f_idx'),
        ),
        migrations.AddIndex(
            model_name='explanation',
            index=models.Index(fields=['explanation_type', 'generated_at'], name='explanation_explana_6aaab8_idx'),
        ),
        migrations.AddIndex(
            model_name='explanation',
            index=models.Index(fields=['cache_key'], name='explanation_cache_k_d923c3_idx'),
        ),
        migrations.AddIndex(
            model_name='explanation',
            index=models.Index(fields=['is_cached'], name='explanation_is_cach_bb3af4_idx'),
        ),
    ]
