# Generated by Django 4.2.16 on 2025-12-01 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('numerology', '0004_create_name_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start_date', models.DateField(db_index=True)),
                ('week_end_date', models.DateField()),
                ('week_number', models.IntegerField(help_text='Week number in the year (1-52)')),
                ('year', models.IntegerField()),
                ('weekly_number', models.IntegerField(help_text='Weekly numerology number')),
                ('personal_year_number', models.IntegerField()),
                ('personal_month_number', models.IntegerField()),
                ('main_theme', models.CharField(max_length=200)),
                ('weekly_summary', models.TextField()),
                ('daily_insights', models.JSONField(default=list, help_text='Day-by-day insights for the week')),
                ('weekly_trends', models.JSONField(default=dict, help_text='Trends and patterns identified')),
                ('recommendations', models.JSONField(default=list, help_text='Recommendations for the week')),
                ('challenges', models.JSONField(default=list, help_text='Potential challenges')),
                ('opportunities', models.JSONField(default=list, help_text='Opportunities for the week')),
                ('raj_yog_status', models.CharField(blank=True, max_length=50, null=True)),
                ('raj_yog_insights', models.TextField(blank=True, null=True)),
                ('llm_summary', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weekly Report',
                'verbose_name_plural': 'Weekly Reports',
                'db_table': 'weekly_reports',
                'ordering': ['-week_start_date'],
            },
        ),
        migrations.CreateModel(
            name='YearlyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_index=True)),
                ('personal_year_number', models.IntegerField()),
                ('personal_year_cycle', models.CharField(help_text='Cycle phase: beginning, middle, or end', max_length=50)),
                ('annual_overview', models.TextField()),
                ('major_themes', models.JSONField(default=list, help_text='Major themes for the year')),
                ('month_by_month', models.JSONField(default=dict, help_text='Month-by-month overview')),
                ('key_dates', models.JSONField(default=list, help_text='Important dates and periods')),
                ('opportunities', models.JSONField(default=list, help_text='Major opportunities')),
                ('challenges', models.JSONField(default=list, help_text='Challenges and remedies')),
                ('recommendations', models.JSONField(default=list, help_text='Yearly recommendations')),
                ('annual_raj_yog_status', models.CharField(blank=True, max_length=50, null=True)),
                ('raj_yog_patterns', models.JSONField(default=list, help_text='Raj Yog patterns throughout the year')),
                ('raj_yog_insights', models.TextField(blank=True, null=True)),
                ('llm_overview', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yearly Report',
                'verbose_name_plural': 'Yearly Reports',
                'db_table': 'yearly_reports',
                'ordering': ['-year'],
            },
        ),
        migrations.RenameIndex(
            model_name='namereport',
            new_name='name_report_user_id_9fd747_idx',
            old_name='name_reports_user_system_idx',
        ),
        migrations.RenameIndex(
            model_name='namereport',
            new_name='name_report_user_id_2efe57_idx',
            old_name='name_reports_user_computed_idx',
        ),
        migrations.RenameIndex(
            model_name='namereport',
            new_name='name_report_name_ty_80b2b0_idx',
            old_name='name_reports_type_system_idx',
        ),
        migrations.AddField(
            model_name='yearlyreport',
            name='explanation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yearly_reports', to='numerology.explanation'),
        ),
        migrations.AddField(
            model_name='yearlyreport',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yearly_reports', to='numerology.person'),
        ),
        migrations.AddField(
            model_name='yearlyreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='explanation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_reports', to='numerology.explanation'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='numerology.person'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='yearlyreport',
            index=models.Index(fields=['user', 'year'], name='yearly_repo_user_id_1a433d_idx'),
        ),
        migrations.AddIndex(
            model_name='yearlyreport',
            index=models.Index(fields=['person', 'year'], name='yearly_repo_person__574627_idx'),
        ),
        migrations.AddIndex(
            model_name='yearlyreport',
            index=models.Index(fields=['year'], name='yearly_repo_year_97eed9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='yearlyreport',
            unique_together={('user', 'person', 'year')},
        ),
        migrations.AddIndex(
            model_name='weeklyreport',
            index=models.Index(fields=['user', 'week_start_date'], name='weekly_repo_user_id_44e8cd_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyreport',
            index=models.Index(fields=['person', 'week_start_date'], name='weekly_repo_person__450812_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyreport',
            index=models.Index(fields=['year', 'week_number'], name='weekly_repo_year_e2d4d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyreport',
            unique_together={('user', 'person', 'week_start_date')},
        ),
    ]
