# Generated by Django 4.2.16 on 2025-12-15 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('numerology', '0005_weeklyreport_yearlyreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_raw', models.TextField(help_text='Original user-entered phone number string')),
                ('phone_e164', models.TextField(help_text='Sanitized E.164 format phone number')),
                ('country', models.CharField(blank=True, help_text='ISO country code', max_length=10, null=True)),
                ('method', models.CharField(choices=[('core', 'Core'), ('full', 'Full'), ('compatibility', 'Compatibility')], default='core', max_length=20)),
                ('computed', models.JSONField(help_text='Computed numbers, breakdowns, evidence_map')),
                ('explanation', models.JSONField(blank=True, help_text='LLM-generated explanation JSON', null=True)),
                ('explanation_error', models.TextField(blank=True, help_text='Error message if LLM explanation failed', null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1, help_text='Algorithm version for reproducibility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phone Report',
                'verbose_name_plural': 'Phone Reports',
                'db_table': 'phone_reports',
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['user', 'computed_at'], name='phone_repor_user_id_b0ec4b_idx'), models.Index(fields=['user', 'method'], name='phone_repor_user_id_957637_idx')],
            },
        ),
        migrations.CreateModel(
            name='DetailedReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reading_type', models.CharField(choices=[('life_path', 'Life Path'), ('destiny', 'Destiny'), ('soul_urge', 'Soul Urge'), ('personality', 'Personality'), ('attitude', 'Attitude'), ('maturity', 'Maturity'), ('balance', 'Balance'), ('full_profile', 'Full Profile')], max_length=50)),
                ('number', models.IntegerField(help_text='The numerology number this reading is for')),
                ('detailed_interpretation', models.TextField(help_text='Comprehensive AI-generated interpretation')),
                ('career_insights', models.TextField(blank=True, help_text='Career-related insights', null=True)),
                ('relationship_insights', models.TextField(blank=True, help_text='Relationship-related insights', null=True)),
                ('life_purpose', models.TextField(blank=True, help_text='Life purpose and mission', null=True)),
                ('challenges_and_growth', models.TextField(blank=True, help_text='Challenges and growth opportunities', null=True)),
                ('personalized_advice', models.TextField(blank=True, help_text='Personalized actionable advice', null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Detailed Reading',
                'verbose_name_plural': 'Detailed Readings',
                'db_table': 'detailed_readings',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['user', 'reading_type'], name='detailed_re_user_id_ed2b60_idx'), models.Index(fields=['user', 'number'], name='detailed_re_user_id_a219bc_idx'), models.Index(fields=['generated_at'], name='detailed_re_generat_7fb3c3_idx')],
                'unique_together': {('user', 'reading_type', 'number')},
            },
        ),
    ]
