# Generated by Django 4.2.16 on 2025-12-16 02:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import numerology.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('numerology', '0006_phonereport_detailedreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='FengShuiAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_address', models.CharField(blank=True, max_length=500)),
                ('house_number', models.CharField(help_text='House/flat number', max_length=50)),
                ('feng_shui_data', models.JSONField(default=dict, help_text='Feng Shui analysis data (directions, elements, etc.)')),
                ('numerology_vibration', models.IntegerField(help_text='Calculated numerology vibration number for the property')),
                ('hybrid_score', models.IntegerField(blank=True, help_text='Overall compatibility score 0-100', null=True)),
                ('recommendations', models.JSONField(default=list, help_text='Space optimization and improvement recommendations')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feng_shui_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feng Shui Analysis',
                'verbose_name_plural': 'Feng Shui Analyses',
                'db_table': 'feng_shui_analyses',
            },
        ),
        migrations.CreateModel(
            name='SpiritualNumerologyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('soul_contracts', models.JSONField(default=list)),
                ('karmic_cycles', models.JSONField(default=list)),
                ('rebirth_cycles', models.JSONField(default=list)),
                ('divine_gifts', models.JSONField(default=list)),
                ('spiritual_alignment', models.JSONField(default=dict)),
                ('past_life_connections', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spiritual_numerology_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spiritual Numerology Profile',
                'verbose_name_plural': 'Spiritual Numerology Profiles',
                'db_table': 'spiritual_numerology_profiles',
            },
        ),
        migrations.CreateModel(
            name='NameCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=200)),
                ('name_type', models.CharField(choices=[('birth', 'Birth'), ('current', 'Current'), ('nickname', 'Nickname')], default='current', max_length=20)),
                ('current_expression', models.IntegerField()),
                ('target_expression', models.IntegerField(blank=True, null=True)),
                ('cultural_context', models.CharField(default='western', max_length=50)),
                ('suggestions', models.JSONField(default=list)),
                ('phonetic_analysis', models.JSONField(default=dict)),
                ('cultural_analysis', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Name Correction',
                'verbose_name_plural': 'Name Corrections',
                'db_table': 'name_corrections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthNumerologyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stress_number', models.IntegerField(help_text='Number indicating stress patterns')),
                ('vitality_number', models.IntegerField(help_text='Number indicating vitality and energy')),
                ('health_cycle_number', models.IntegerField(help_text='Current health cycle number')),
                ('health_cycles', models.JSONField(default=dict, help_text='9-year and 7-year health cycles')),
                ('current_cycle', models.JSONField(default=dict, help_text='Current health cycle details')),
                ('medical_timing', models.JSONField(default=dict, help_text='Optimal timing for medical procedures')),
                ('health_windows', models.JSONField(default=list, help_text='Yearly health windows')),
                ('risk_periods', models.JSONField(default=list, help_text='Identified health risk periods')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_numerology_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Numerology Profile',
                'verbose_name_plural': 'Health Numerology Profiles',
                'db_table': 'health_numerology_profiles',
            },
        ),
        migrations.CreateModel(
            name='GenerationalAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_unit_hash', models.CharField(db_index=True, help_text='Hash of family member IDs for uniqueness', max_length=64)),
                ('generational_number', models.IntegerField(help_text='Calculated generational number for the family unit')),
                ('analysis_data', models.JSONField(default=dict, help_text='Detailed generational analysis including patterns, cycles, etc.')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generational_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generational Analysis',
                'verbose_name_plural': 'Generational Analyses',
                'db_table': 'generational_analyses',
            },
        ),
        migrations.CreateModel(
            name='SpaceOptimization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(help_text='Name of the room/space', max_length=200)),
                ('room_number', models.CharField(blank=True, help_text='Room number if applicable', max_length=50, null=True)),
                ('direction', models.CharField(blank=True, help_text='Direction/orientation of the room', max_length=50, null=True)),
                ('color_recommendations', models.JSONField(default=list, help_text='Recommended colors for this space')),
                ('number_combinations', models.JSONField(default=list, help_text='Favorable number combinations')),
                ('energy_flow_score', models.IntegerField(blank=True, help_text='Energy flow score 0-100', null=True)),
                ('layout_suggestions', models.JSONField(default=list, help_text='Layout and arrangement suggestions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_optimizations', to='numerology.fengshuianalysis')),
            ],
            options={
                'verbose_name': 'Space Optimization',
                'verbose_name_plural': 'Space Optimizations',
                'db_table': 'space_optimizations',
                'indexes': [models.Index(fields=['analysis', 'room_name'], name='space_optim_analysi_58d360_idx')],
            },
        ),
        migrations.CreateModel(
            name='PredictiveCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_type', models.CharField(choices=[('nine_year', '9-Year Cycle'), ('breakthrough', 'Breakthrough Year'), ('crisis', 'Crisis Year'), ('opportunity', 'Opportunity Period')], max_length=50)),
                ('year', models.IntegerField()),
                ('cycle_data', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictive_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Predictive Cycle',
                'verbose_name_plural': 'Predictive Cycles',
                'db_table': 'predictive_cycles',
                'ordering': ['year'],
                'indexes': [models.Index(fields=['user', 'year'], name='predictive__user_id_6dc8ec_idx'), models.Index(fields=['cycle_type'], name='predictive__cycle_t_8f5e2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='MentalStateTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('emotional_state', models.CharField(choices=[('very_positive', 'Very Positive'), ('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('very_negative', 'Very Negative')], max_length=20)),
                ('stress_level', models.IntegerField(help_text='Stress level 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mood_score', models.IntegerField(help_text='Mood score 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('numerology_cycle', models.CharField(blank=True, help_text="Current numerology cycle (e.g., 'Personal Year 7')", max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='User notes about their state')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mental_state_trackings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mental State Tracking',
                'verbose_name_plural': 'Mental State Trackings',
                'db_table': 'mental_state_trackings',
                'indexes': [models.Index(fields=['user', 'date'], name='mental_stat_user_id_43af12_idx'), models.Index(fields=['emotional_state'], name='mental_stat_emotion_9f4482_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MentalStateAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('stress_patterns', models.JSONField(default=numerology.models.default_dict, help_text='Identified stress patterns and correlations')),
                ('wellbeing_recommendations', models.JSONField(default=numerology.models.default_list, help_text='AI-generated wellbeing recommendations')),
                ('mood_predictions', models.JSONField(default=numerology.models.default_dict, help_text='Predicted mood cycles based on numerology')),
                ('emotional_compatibility', models.JSONField(default=numerology.models.default_dict, help_text='Emotional compatibility analysis with others')),
                ('numerology_correlations', models.JSONField(default=numerology.models.default_dict, help_text='Correlations between numerology cycles and mental state')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mental_state_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mental State Analysis',
                'verbose_name_plural': 'Mental State Analyses',
                'db_table': 'mental_state_analyses',
                'indexes': [models.Index(fields=['user', 'period_start', 'period_end'], name='mental_stat_user_id_8d16f6_idx'), models.Index(fields=['calculated_at'], name='mental_stat_calcula_36044b_idx')],
            },
        ),
        migrations.CreateModel(
            name='KarmicContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_type', models.CharField(blank=True, choices=[('teaching', 'Teaching Contract'), ('learning', 'Learning Contract'), ('healing', 'Healing Contract'), ('karmic_debt', 'Karmic Debt Contract'), ('soul_evolution', 'Soul Evolution Contract'), ('neutral', 'Neutral Relationship')], max_length=50, null=True)),
                ('karmic_lessons', models.JSONField(default=list, help_text='List of karmic lessons to be learned')),
                ('compatibility_score', models.IntegerField(blank=True, help_text='Compatibility score 0-100', null=True)),
                ('analysis_data', models.JSONField(default=dict, help_text='Detailed karmic contract analysis')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karmic_contracts_as_child', to='numerology.person')),
                ('parent_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karmic_contracts_as_parent', to='numerology.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karmic_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Karmic Contract',
                'verbose_name_plural': 'Karmic Contracts',
                'db_table': 'karmic_contracts',
                'indexes': [models.Index(fields=['user', 'calculated_at'], name='karmic_cont_user_id_09e243_idx'), models.Index(fields=['parent_person', 'child_person'], name='karmic_cont_parent__512563_idx'), models.Index(fields=['contract_type'], name='karmic_cont_contrac_ee59d6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='karmiccontract',
            constraint=models.CheckConstraint(check=models.Q(('parent_person', models.F('child_person')), _negated=True), name='different_parent_child'),
        ),
        migrations.AlterUniqueTogether(
            name='karmiccontract',
            unique_together={('user', 'parent_person', 'child_person')},
        ),
        migrations.AddIndex(
            model_name='generationalanalysis',
            index=models.Index(fields=['user', 'calculated_at'], name='generationa_user_id_720e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='generationalanalysis',
            index=models.Index(fields=['generational_number'], name='generationa_generat_04b57d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='generationalanalysis',
            unique_together={('user', 'family_unit_hash')},
        ),
        migrations.AddIndex(
            model_name='fengshuianalysis',
            index=models.Index(fields=['user', 'calculated_at'], name='feng_shui_a_user_id_8c134d_idx'),
        ),
        migrations.AddIndex(
            model_name='fengshuianalysis',
            index=models.Index(fields=['numerology_vibration'], name='feng_shui_a_numerol_3414f0_idx'),
        ),
    ]
