# Generated by Django 4.2.16 on 2026-01-09 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('numerology', '0008_add_chaldean_zodiac_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakthroughYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_index=True)),
                ('personal_year', models.IntegerField()),
                ('breakthrough_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('preparation', models.TextField(help_text='Preparation advice for this breakthrough')),
                ('confidence_score', models.IntegerField(default=75, help_text='Confidence in prediction (0-100)')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Breakthrough Year',
                'verbose_name_plural': 'Breakthrough Years',
                'db_table': 'breakthrough_years',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='CrisisYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_index=True)),
                ('personal_year', models.IntegerField()),
                ('crisis_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('guidance', models.TextField(help_text='Guidance for navigating this crisis')),
                ('severity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('preparation_steps', models.JSONField(default=list, help_text='Steps to prepare for this crisis')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crisis Year',
                'verbose_name_plural': 'Crisis Years',
                'db_table': 'crisis_years',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='EmotionalCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_type', models.CharField(choices=[('daily', 'Daily Cycle'), ('weekly', 'Weekly Cycle'), ('monthly', 'Monthly Cycle'), ('yearly', 'Yearly Cycle')], max_length=50)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField()),
                ('predicted_mood', models.CharField(help_text='Predicted emotional state', max_length=50)),
                ('mood_score_range', models.JSONField(default=list, help_text='Predicted mood score range [min, max]')),
                ('energy_level', models.CharField(choices=[('low', 'Low'), ('low-moderate', 'Low-Moderate'), ('moderate', 'Moderate'), ('moderate-high', 'Moderate-High'), ('high', 'High')], max_length=20)),
                ('recommendations', models.JSONField(default=list, help_text='Emotional wellbeing recommendations')),
                ('personal_year', models.IntegerField(blank=True, null=True)),
                ('personal_month', models.IntegerField(blank=True, null=True)),
                ('personal_day', models.IntegerField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Emotional Cycle',
                'verbose_name_plural': 'Emotional Cycles',
                'db_table': 'emotional_cycles',
            },
        ),
        migrations.CreateModel(
            name='FamilyUnitProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('family_unit_hash', models.CharField(db_index=True, max_length=64)),
                ('member_count', models.IntegerField()),
                ('family_life_path', models.IntegerField(help_text='Combined life path for family unit')),
                ('family_destiny', models.IntegerField(blank=True, null=True)),
                ('generational_number', models.IntegerField()),
                ('compatibility_score', models.IntegerField(default=50, help_text='Overall family compatibility (0-100)')),
                ('dynamics', models.JSONField(default=dict, help_text='Family dynamics analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Family Unit Profile',
                'verbose_name_plural': 'Family Unit Profiles',
                'db_table': 'family_unit_profiles',
            },
        ),
        migrations.CreateModel(
            name='KarmicTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('cycle_number', models.IntegerField(help_text='Karmic cycle number')),
                ('karmic_theme', models.CharField(max_length=200)),
                ('lessons', models.JSONField(default=list)),
                ('is_current', models.BooleanField(default=False)),
                ('timeline_data', models.JSONField(default=dict, help_text='Additional timeline visualization data')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Karmic Timeline',
                'verbose_name_plural': 'Karmic Timelines',
                'db_table': 'karmic_timelines',
            },
        ),
        migrations.CreateModel(
            name='LifeMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(db_index=True)),
                ('age', models.IntegerField(help_text='Age at this milestone')),
                ('milestone_type', models.CharField(max_length=100)),
                ('significance', models.TextField()),
                ('life_path_number', models.IntegerField(blank=True, null=True)),
                ('destiny_number', models.IntegerField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Life Milestone',
                'verbose_name_plural': 'Life Milestones',
                'db_table': 'life_milestones',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='RebirthCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rebirth_number', models.IntegerField(help_text='Rebirth cycle number')),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('duration_years', models.IntegerField(default=27, help_text='Duration of rebirth cycle in years')),
                ('transformation_theme', models.CharField(max_length=200)),
                ('spiritual_growth', models.TextField(help_text='Description of spiritual growth in this cycle')),
                ('is_current', models.BooleanField(default=False)),
                ('transition_warnings', models.JSONField(default=list, help_text='Warnings for cycle transitions')),
                ('preparation_guidance', models.JSONField(default=list, help_text='Guidance for preparing for transitions')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rebirth Cycle',
                'verbose_name_plural': 'Rebirth Cycles',
                'db_table': 'rebirth_cycles',
            },
        ),
        migrations.CreateModel(
            name='RemedyCombination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('combination_score', models.FloatField(help_text='Compatibility score 0-10')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Remedy Combination',
                'verbose_name_plural': 'Remedy Combinations',
                'db_table': 'remedy_combinations',
                'ordering': ['-combination_score'],
            },
        ),
        migrations.CreateModel(
            name='RemedyEffectiveness',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effectiveness_score', models.FloatField(help_text='Average effectiveness score 0-5')),
                ('feedback', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
            ],
            options={
                'verbose_name': 'Remedy Effectiveness',
                'verbose_name_plural': 'Remedy Effectiveness Records',
                'db_table': 'remedy_effectiveness',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='RemedyReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='daily', max_length=20)),
                ('reminder_time', models.TimeField(help_text='Time to send reminder')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_send_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Remedy Reminder',
                'verbose_name_plural': 'Remedy Reminders',
                'db_table': 'remedy_reminders',
                'ordering': ['next_send_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomNumerology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=200)),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('direction', models.CharField(blank=True, max_length=50, null=True)),
                ('room_vibration', models.IntegerField(blank=True, help_text='Room numerology vibration number', null=True)),
                ('direction_compatibility', models.JSONField(default=dict, help_text='Direction compatibility analysis')),
                ('color_recommendations', models.JSONField(default=list)),
                ('number_recommendations', models.JSONField(default=list)),
                ('layout_recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room Numerology',
                'verbose_name_plural': 'Room Numerology',
                'db_table': 'room_numerology',
            },
        ),
        migrations.CreateModel(
            name='SoulContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.IntegerField(help_text='The soul contract number (1-9)')),
                ('contract_type', models.CharField(choices=[('primary', 'Primary Contract'), ('secondary', 'Secondary Contract'), ('karmic', 'Karmic Contract'), ('soul_evolution', 'Soul Evolution Contract')], max_length=20)),
                ('description', models.TextField(help_text='Description of the soul contract')),
                ('lessons', models.JSONField(default=list, help_text='List of lessons associated with this contract')),
                ('fulfillment_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Soul Contract',
                'verbose_name_plural': 'Soul Contracts',
                'db_table': 'soul_contracts',
            },
        ),
        migrations.AddField(
            model_name='predictivecycle',
            name='confidence_score',
            field=models.IntegerField(blank=True, help_text='Prediction confidence (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='predictivecycle',
            name='severity_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='remedy',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='remedy',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Expected duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='remedy',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='remedy',
            name='personalization_data',
            field=models.JSONField(blank=True, default=dict, help_text='AI-generated personalization data'),
        ),
        migrations.AddField(
            model_name='remedy',
            name='priority',
            field=models.IntegerField(default=5, help_text='Priority level 1-10'),
        ),
        migrations.AddField(
            model_name='remedytracking',
            name='effectiveness_rating',
            field=models.IntegerField(blank=True, help_text='User rating 1-5', null=True),
        ),
        migrations.AddField(
            model_name='remedytracking',
            name='mood_after',
            field=models.CharField(blank=True, choices=[('very_low', 'Very Low'), ('low', 'Low'), ('neutral', 'Neutral'), ('good', 'Good'), ('very_good', 'Very Good')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='remedytracking',
            name='mood_before',
            field=models.CharField(blank=True, choices=[('very_low', 'Very Low'), ('low', 'Low'), ('neutral', 'Neutral'), ('good', 'Good'), ('very_good', 'Very Good')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='predictivecycle',
            index=models.Index(fields=['confidence_score'], name='predictive__confide_5401de_idx'),
        ),
        migrations.AddIndex(
            model_name='spiritualnumerologyprofile',
            index=models.Index(fields=['user', 'calculated_at'], name='spiritual_n_user_id_51569d_idx'),
        ),
        migrations.AddField(
            model_name='soulcontract',
            name='spiritual_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='numerology.spiritualnumerologyprofile'),
        ),
        migrations.AddField(
            model_name='soulcontract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soul_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roomnumerology',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_numerology', to='numerology.fengshuianalysis'),
        ),
        migrations.AddField(
            model_name='remedyreminder',
            name='remedy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='numerology.remedy'),
        ),
        migrations.AddField(
            model_name='remedyreminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remedy_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remedyeffectiveness',
            name='remedy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectiveness_records', to='numerology.remedy'),
        ),
        migrations.AddField(
            model_name='remedyeffectiveness',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remedy_effectiveness', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remedycombination',
            name='primary_remedy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_primary_combination', to='numerology.remedy'),
        ),
        migrations.AddField(
            model_name='remedycombination',
            name='secondary_remedy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_secondary_combination', to='numerology.remedy'),
        ),
        migrations.AddField(
            model_name='remedycombination',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remedy_combinations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rebirthcycle',
            name='spiritual_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rebirth_cycles_list', to='numerology.spiritualnumerologyprofile'),
        ),
        migrations.AddField(
            model_name='rebirthcycle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebirth_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lifemilestone',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='karmictimeline',
            name='spiritual_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karmic_timelines', to='numerology.spiritualnumerologyprofile'),
        ),
        migrations.AddField(
            model_name='karmictimeline',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karmic_timelines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyunitprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_unit_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emotionalcycle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotional_cycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crisisyear',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crisis_years', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breakthroughyear',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakthrough_years', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='soulcontract',
            index=models.Index(fields=['user', 'contract_type'], name='soul_contra_user_id_c8a2cd_idx'),
        ),
        migrations.AddIndex(
            model_name='soulcontract',
            index=models.Index(fields=['contract_number'], name='soul_contra_contrac_45c0d0_idx'),
        ),
        migrations.AddIndex(
            model_name='soulcontract',
            index=models.Index(fields=['fulfillment_status'], name='soul_contra_fulfill_16b81e_idx'),
        ),
        migrations.AddIndex(
            model_name='roomnumerology',
            index=models.Index(fields=['analysis', 'room_name'], name='room_numero_analysi_4a466f_idx'),
        ),
        migrations.AddIndex(
            model_name='remedyreminder',
            index=models.Index(fields=['user', 'is_active'], name='remedy_remi_user_id_e14578_idx'),
        ),
        migrations.AddIndex(
            model_name='remedyreminder',
            index=models.Index(fields=['next_send_at', 'is_active'], name='remedy_remi_next_se_e9215b_idx'),
        ),
        migrations.AddIndex(
            model_name='remedyeffectiveness',
            index=models.Index(fields=['user', 'remedy'], name='remedy_effe_user_id_1696cc_idx'),
        ),
        migrations.AddIndex(
            model_name='remedyeffectiveness',
            index=models.Index(fields=['analyzed_at'], name='remedy_effe_analyze_94358e_idx'),
        ),
        migrations.AddIndex(
            model_name='remedycombination',
            index=models.Index(fields=['user', 'is_active'], name='remedy_comb_user_id_42a705_idx'),
        ),
        migrations.AddIndex(
            model_name='rebirthcycle',
            index=models.Index(fields=['user', 'start_year'], name='rebirth_cyc_user_id_df225e_idx'),
        ),
        migrations.AddIndex(
            model_name='rebirthcycle',
            index=models.Index(fields=['is_current'], name='rebirth_cyc_is_curr_b9ccb5_idx'),
        ),
        migrations.AddIndex(
            model_name='rebirthcycle',
            index=models.Index(fields=['rebirth_number'], name='rebirth_cyc_rebirth_d35a5a_idx'),
        ),
        migrations.AddIndex(
            model_name='lifemilestone',
            index=models.Index(fields=['user', 'year'], name='life_milest_user_id_5e7a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='lifemilestone',
            index=models.Index(fields=['milestone_type'], name='life_milest_milesto_3c8af8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lifemilestone',
            unique_together={('user', 'year', 'milestone_type')},
        ),
        migrations.AddIndex(
            model_name='karmictimeline',
            index=models.Index(fields=['user', 'start_year'], name='karmic_time_user_id_6c7dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='karmictimeline',
            index=models.Index(fields=['is_current'], name='karmic_time_is_curr_b51096_idx'),
        ),
        migrations.AddIndex(
            model_name='karmictimeline',
            index=models.Index(fields=['cycle_number'], name='karmic_time_cycle_n_be55b2_idx'),
        ),
        migrations.AddIndex(
            model_name='familyunitprofile',
            index=models.Index(fields=['user', 'family_unit_hash'], name='family_unit_user_id_8e4f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='emotionalcycle',
            index=models.Index(fields=['user', 'start_date'], name='emotional_c_user_id_92082f_idx'),
        ),
        migrations.AddIndex(
            model_name='emotionalcycle',
            index=models.Index(fields=['cycle_type'], name='emotional_c_cycle_t_a038e6_idx'),
        ),
        migrations.AddIndex(
            model_name='crisisyear',
            index=models.Index(fields=['user', 'year'], name='crisis_year_user_id_04d36e_idx'),
        ),
        migrations.AddIndex(
            model_name='crisisyear',
            index=models.Index(fields=['severity_level'], name='crisis_year_severit_dda2a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='crisisyear',
            unique_together={('user', 'year')},
        ),
        migrations.AddIndex(
            model_name='breakthroughyear',
            index=models.Index(fields=['user', 'year'], name='breakthroug_user_id_c8aebd_idx'),
        ),
        migrations.AddIndex(
            model_name='breakthroughyear',
            index=models.Index(fields=['personal_year'], name='breakthroug_persona_6f3017_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='breakthroughyear',
            unique_together={('user', 'year')},
        ),
    ]
