# Generated by Django 4.2.16 on 2026-02-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numerology', '0010_add_profile_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='numerologyprofile',
            new_name='numerology__user_id_7ca2a3_idx',
            old_name='numerology_user_ca_idx',
        ),
        migrations.RenameIndex(
            model_name='numerologyprofile',
            new_name='numerology__calcula_4a2bf1_idx',
            old_name='numerology_calc_sy_idx',
        ),
        migrations.RenameIndex(
            model_name='numerologyprofile',
            new_name='numerology__updated_ccf128_idx',
            old_name='numerology_updated_idx',
        ),
    ]
