import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { AlertCircleIcon, CalendarIcon, StarIcon } from 'lucide-react';
import { CosmicPageLayout } from '../components/CosmicPageLayout';
import { SpaceCard } from '../components/SpaceCard';
import { TouchOptimizedButton } from '../components/TouchOptimizedButton';
import { useAuth } from '../contexts/AuthContext';
import { numerologyAPI } from '../lib/numerology-api';

const currentMonth = new Date().toISOString().slice(0, 7);

export function AuspiciousDates() {
  const { user } = useAuth();
  const [month, setMonth] = useState(currentMonth);
  const [eventType, setEventType] = useState('general');
  const [dates, setDates] = useState<any[]>([]);
  const [recommendations, setRecommendations] = useState<string[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const loadDates = async () => {
    const birthDate = user?.date_of_birth || user?.birthDate;
    if (!birthDate) {
      setError('Add your date of birth in Profile before requesting auspicious dates.');
      return;
    }
    const [year, monthNumber] = month.split('-').map(Number);
    const endDate = new Date(year, monthNumber, 0).toISOString().slice(0, 10);
    setIsLoading(true);
    setError(null);
    try {
      const response = await numerologyAPI.findBestDates({ birth_date: birthDate, event_type: eventType, start_date: `${month}-01`, end_date: endDate });
      setDates(response.best_dates || []);
      setRecommendations(response.recommendations || []);
    } catch (err: any) {
      setDates([]);
      setRecommendations([]);
      setError(err?.response?.data?.error || 'Unable to load auspicious dates.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <CosmicPageLayout>
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
        <div className="flex items-center gap-4 mb-4"><div className="w-12 h-12 rounded-xl bg-gradient-to-br from-purple-500 to-indigo-600 flex items-center justify-center shadow-lg"><CalendarIcon className="w-6 h-6 text-white" /></div><div><h1 className="text-4xl md:text-5xl font-['Playfair_Display'] font-bold text-white">Auspicious Dates</h1><p className="text-white/70">Personalized dates generated by the timing numerology service</p></div></div>
      </motion.div>

      <SpaceCard variant="premium" className="p-6 md:p-8 mb-8">
        <div className="grid md:grid-cols-2 gap-4">
          <div><label htmlFor="auspiciousMonth" className="block text-sm font-medium text-white mb-2">Month</label><input id="auspiciousMonth" type="month" value={month} onChange={(event) => setMonth(event.target.value)} className="w-full px-4 py-3 bg-[#0a1628]/60 border border-cyan-500/20 rounded-xl text-white" /></div>
          <div><label htmlFor="eventType" className="block text-sm font-medium text-white mb-2">Event type</label><select id="eventType" value={eventType} onChange={(event) => setEventType(event.target.value)} className="w-full px-4 py-3 bg-[#0a1628]/60 border border-cyan-500/20 rounded-xl text-white"><option value="general">General</option><option value="business_launch">Business launch</option><option value="wedding">Wedding</option><option value="purchase">Purchase</option><option value="travel">Travel</option><option value="meeting">Meeting</option></select></div>
        </div>
        <TouchOptimizedButton variant="primary" size="lg" onClick={loadDates} disabled={isLoading} className="w-full mt-6" ariaLabel="Find auspicious dates">{isLoading ? 'Finding dates...' : 'Find Dates'}</TouchOptimizedButton>
        {error && <p className="text-red-400 mt-4" role="alert">{error}</p>}
      </SpaceCard>

      <div className="space-y-6">
        {dates.map((item) => <SpaceCard key={item.date} variant="default" className="p-6"><div className="flex items-start justify-between gap-4 mb-4"><div><h2 className="text-2xl font-['Playfair_Display'] font-bold text-white">{new Date(`${item.date}T00:00:00`).toLocaleDateString(undefined, { dateStyle: 'full' })}</h2><p className="text-white/60">Personal day {item.personal_day} · Universal day {item.universal_day}</p></div><div className="flex items-center gap-2 text-yellow-400"><StarIcon className="w-5 h-5 fill-current" /><span className="text-xl font-bold">{item.score}/100</span></div></div><p className="text-cyan-300 font-medium mb-3">{item.level}</p><p className="text-white/80">{item.explanation}</p>{item.alignment && <p className="text-white/60 mt-3">{item.alignment}</p>}</SpaceCard>)}
        {!isLoading && !error && dates.length === 0 && <SpaceCard variant="default" className="p-6"><p className="text-white/70">Choose a month and event type to receive a server-generated timing analysis.</p></SpaceCard>}
        {recommendations.length > 0 && <SpaceCard variant="premium" className="p-6"><h2 className="flex items-center gap-2 text-xl font-semibold text-white mb-3"><AlertCircleIcon className="w-5 h-5" />Recommendations</h2><ul className="space-y-2 text-white/70">{recommendations.map((recommendation) => <li key={recommendation}>{recommendation}</li>)}</ul></SpaceCard>}
      </div>
    </CosmicPageLayout>
  );
}
