# Generated by Django 4.2.16 on 2025-11-30 04:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_type', models.CharField(choices=[('personal_year', 'Personal Year'), ('personal_month', 'Personal Month'), ('personal_day', 'Personal Day')], max_length=20)),
                ('cycle_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Cycle',
                'verbose_name_plural': 'Personal Cycles',
                'db_table': 'personal_cycles',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['user', 'start_date'], name='personal_cy_user_id_97f7c6_idx'), models.Index(fields=['user', 'cycle_type'], name='personal_cy_user_id_b2e0db_idx')],
            },
        ),
        migrations.CreateModel(
            name='NumerologyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('personal_year_start', 'Personal Year Start'), ('personal_month_start', 'Personal Month Start'), ('pinnacle_cycle', 'Pinnacle Cycle'), ('challenge_period', 'Challenge Period'), ('auspicious_day', 'Auspicious Day'), ('remedy_day', 'Remedy Practice Day')], max_length=50)),
                ('event_date', models.DateField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('numerology_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(33)])),
                ('importance', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numerology_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Numerology Event',
                'verbose_name_plural': 'Numerology Events',
                'db_table': 'numerology_events',
                'ordering': ['event_date', 'importance'],
                'indexes': [models.Index(fields=['user', 'event_date'], name='numerology__user_id_208f67_idx'), models.Index(fields=['user', 'event_type'], name='numerology__user_id_0aedc7_idx'), models.Index(fields=['event_date', 'importance'], name='numerology__event_d_174290_idx')],
            },
        ),
        migrations.CreateModel(
            name='CalendarReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('remedy', 'Remedy Practice'), ('meditation', 'Meditation'), ('affirmation', 'Affirmation'), ('cycle_change', 'Cycle Change'), ('custom', 'Custom')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('reminder_date', models.DateField()),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('numerology_context', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Reminder',
                'verbose_name_plural': 'Calendar Reminders',
                'db_table': 'calendar_reminders',
                'ordering': ['reminder_date', 'reminder_time'],
                'indexes': [models.Index(fields=['user', 'reminder_date'], name='calendar_re_user_id_c6e7da_idx'), models.Index(fields=['user', 'is_completed'], name='calendar_re_user_id_96def5_idx'), models.Index(fields=['reminder_date', 'is_completed'], name='calendar_re_reminde_46e201_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuspiciousDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('wedding', 'Wedding'), ('business_start', 'Business Start'), ('travel', 'Travel'), ('important_decision', 'Important Decision'), ('health_treatment', 'Health Treatment'), ('education_start', 'Education Start'), ('property_purchase', 'Property Purchase'), ('other', 'Other')], max_length=50)),
                ('activity_description', models.CharField(blank=True, max_length=500)),
                ('auspicious_date', models.DateField()),
                ('numerology_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('reasoning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auspicious_dates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auspicious Date',
                'verbose_name_plural': 'Auspicious Dates',
                'db_table': 'auspicious_dates',
                'ordering': ['auspicious_date', '-numerology_score'],
                'indexes': [models.Index(fields=['user', 'auspicious_date'], name='auspicious__user_id_afafe2_idx'), models.Index(fields=['user', 'activity_type'], name='auspicious__user_id_1158c2_idx')],
            },
        ),
    ]
