# Generated by Django 4.2.16 on 2025-11-30 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('group_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_created', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='social_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('compatibility_shared', 'Compatibility Shared'), ('insight_shared', 'Insight Shared'), ('profile_viewed', 'Profile Viewed')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['from_user', 'to_user'], name='interaction_from_us_232f6d_idx'), models.Index(fields=['interaction_type', 'created_at'], name='interaction_interac_c2785c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection_type', models.CharField(choices=[('friend', 'Friend'), ('follower', 'Follower'), ('following', 'Following'), ('blocked', 'Blocked')], default='friend', max_length=20)),
                ('is_mutual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_initiated', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'connections',
                'indexes': [models.Index(fields=['user1', 'connection_type'], name='connections_user1_i_ce47e9_idx'), models.Index(fields=['user2', 'connection_type'], name='connections_user2_i_8c62d1_idx')],
                'unique_together': {('user1', 'user2')},
            },
        ),
    ]
