# Generated by Django 4.2.16 on 2025-11-30 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumerologyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('compatibility_rule', 'Compatibility Rule'), ('timing_rule', 'Timing Rule'), ('life_path_rule', 'Life Path Rule'), ('cycle_rule', 'Cycle Rule')], max_length=50)),
                ('rule_name', models.CharField(max_length=200)),
                ('rule_condition', models.JSONField()),
                ('rule_result', models.TextField()),
                ('examples', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Numerology Rule',
                'verbose_name_plural': 'Numerology Rules',
                'db_table': 'numerology_rules',
                'ordering': ['rule_type', 'rule_name'],
                'indexes': [models.Index(fields=['rule_type', 'is_active'], name='numerology__rule_ty_4b573a_idx')],
            },
        ),
        migrations.CreateModel(
            name='NumberRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number1', models.IntegerField(db_index=True)),
                ('number2', models.IntegerField(db_index=True)),
                ('relationship_type', models.CharField(choices=[('compatible', 'Compatible'), ('challenging', 'Challenging'), ('complementary', 'Complementary'), ('neutral', 'Neutral'), ('master_pair', 'Master Pair')], max_length=50)),
                ('strength', models.IntegerField(default=5)),
                ('description', models.TextField()),
                ('examples', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Number Relationship',
                'verbose_name_plural': 'Number Relationships',
                'db_table': 'number_relationships',
                'indexes': [models.Index(fields=['number1', 'number2'], name='number_rela_number1_fa8502_idx'), models.Index(fields=['relationship_type'], name='number_rela_relatio_e20b9f_idx')],
                'unique_together': {('number1', 'number2')},
            },
        ),
        migrations.CreateModel(
            name='NumerologyPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern_type', models.CharField(choices=[('sequence', 'Number Sequence'), ('cycle', 'Cycle Pattern'), ('combination', 'Number Combination'), ('trend', 'Trend Pattern')], max_length=50)),
                ('pattern_data', models.JSONField()),
                ('description', models.TextField()),
                ('significance', models.TextField()),
                ('confidence_score', models.FloatField(default=0.5)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numerology_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Numerology Pattern',
                'verbose_name_plural': 'Numerology Patterns',
                'db_table': 'numerology_patterns',
                'ordering': ['-confidence_score', '-discovered_at'],
                'indexes': [models.Index(fields=['user', 'pattern_type'], name='numerology__user_id_d7fbe0_idx'), models.Index(fields=['pattern_type', 'confidence_score'], name='numerology__pattern_4a17e7_idx')],
            },
        ),
    ]
