# Generated by Django 4.2.7 on 2024-06-15 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_name', models.CharField(max_length=100)),
                ('partner_birth_date', models.DateField()),
                ('relationship_type', models.CharField(choices=[('romantic', 'Romantic'), ('business', 'Business'), ('friendship', 'Friendship'), ('family', 'Family')], max_length=20)),
                ('compatibility_score', models.IntegerField()),
                ('strengths', models.JSONField(default=list)),
                ('challenges', models.JSONField(default=list)),
                ('advice', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compatibility Check',
                'verbose_name_plural': 'Compatibility Checks',
                'db_table': 'compatibility_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('specialty', models.CharField(choices=[('relationship', 'Relationship & Compatibility'), ('career', 'Career & Business'), ('spiritual', 'Spiritual Growth'), ('health', 'Health & Wellness'), ('general', 'General Numerology')], max_length=20)),
                ('experience_years', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('bio', models.TextField()),
                ('profile_picture_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expert',
                'verbose_name_plural': 'Experts',
                'db_table': 'experts',
                'ordering': ['-rating', '-experience_years'],
            },
        ),
        migrations.CreateModel(
            name='Remedy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remedy_type', models.CharField(choices=[('gemstone', 'Gemstone'), ('color', 'Color'), ('ritual', 'Ritual'), ('mantra', 'Mantra'), ('dietary', 'Dietary'), ('exercise', 'Exercise')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommendation', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remedies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remedy',
                'verbose_name_plural': 'Remedies',
                'db_table': 'remedies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_type', models.CharField(choices=[('video', 'Video Call'), ('chat', 'Chat'), ('phone', 'Phone Call')], max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='core.expert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'db_table': 'consultations',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='RemedyTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remedy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='core.remedy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remedy_trackings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remedy Tracking',
                'verbose_name_plural': 'Remedy Trackings',
                'db_table': 'remedy_trackings',
                'ordering': ['-date'],
                'unique_together': {('user', 'remedy', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ConsultationReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('review_text', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.consultation')),
            ],
            options={
                'verbose_name': 'Consultation Review',
                'verbose_name_plural': 'Consultation Reviews',
                'db_table': 'consultation_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='compatibilitycheck',
            index=models.Index(fields=['user', 'created_at'], name='compatibilit_user_id_3f8b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='compatibilitycheck',
            index=models.Index(fields=['relationship_type'], name='compatibilit_relation_2e8b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='remedy',
            index=models.Index(fields=['user', 'remedy_type'], name='core_remedy_user_id_3f8b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='remedy',
            index=models.Index(fields=['is_active'], name='core_remedy_is_acti_3f8b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['user', 'scheduled_at'], name='core_consul_user_id_3f8b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['expert', 'scheduled_at'], name='core_consul_expert__4e8b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['status'], name='core_consul_status_3f8b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='remedytracking',
            index=models.Index(fields=['user', 'date'], name='remedy_trac_user_id_3f8b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='remedytracking',
            index=models.Index(fields=['remedy', 'date'], name='remedy_trac_remedy__4e8b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationreview',
            index=models.Index(fields=['consultation'], name='consultatio_consulta_3f8b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationreview',
            index=models.Index(fields=['rating'], name='consultatio_rating_3f8b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='expert',
            index=models.Index(fields=['specialty', 'is_active'], name='core_exper_special_3f8b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='expert',
            index=models.Index(fields=['rating'], name='core_exper_rating_3f8b4a_idx'),
        ),
    ]