# Generated by Django 4.2.7 on 2025-11-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_numerai_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerologyprofile',
            name='karmic_debt_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='numerologyprofile',
            name='hidden_passion_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='numerologyprofile',
            name='subconscious_self_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]