# Generated by Django 4.2.16 on 2025-11-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_create_new_models'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameIndex(
                    model_name='compatibilitycheck',
                    new_name='compatibili_user_id_cae1ee_idx',
                    old_name='compatibilit_user_id_3f8b4a_idx',
                ),
                migrations.RenameIndex(
                    model_name='compatibilitycheck',
                    new_name='compatibili_relatio_cd3cc4_idx',
                    old_name='compatibilit_relation_2e8b4a_idx',
                ),
                migrations.RenameIndex(
                    model_name='consultation',
                    new_name='consultatio_user_id_68d40d_idx',
                    old_name='core_consul_user_id_3f8b4a_idx',
                ),
                migrations.RenameIndex(
                    model_name='consultation',
                    new_name='consultatio_expert__73f6b2_idx',
                    old_name='core_consul_expert__4e8b4a_idx',
                ),
                migrations.RenameIndex(
                    model_name='consultation',
                    new_name='consultatio_status_beb187_idx',
                    old_name='core_consul_status_3f8b4a_idx',
                ),
                migrations.RenameIndex(
                    model_name='consultationreview',
                    new_name='consultatio_consult_83762f_idx',
                    old_name='consultatio_consulta_3f8b4a_idx',
                ),
                migrations.RenameIndex(
                    model_name='consultationreview',
                    new_name='consultatio_rating_8fcb28_idx',
                    old_name='consultatio_rating_3f8b4a_idx',
                ),
                migrations.RenameIndex(
                    model_name='expert',
                    new_name='experts_special_61ffdd_idx',
                    old_name='core_exper_special_3f8b4a_idx',
                ),
                migrations.RenameIndex(
                    model_name='expert',
                    new_name='experts_rating_47b7e6_idx',
                    old_name='core_exper_rating_3f8b4a_idx',
                ),
                migrations.RenameIndex(
                    model_name='remedy',
                    new_name='remedies_user_id_136d3e_idx',
                    old_name='core_remedy_user_id_3f8b4a_idx',
                ),
                migrations.RenameIndex(
                    model_name='remedy',
                    new_name='remedies_is_acti_41f20b_idx',
                    old_name='core_remedy_is_acti_3f8b4a_idx',
                ),
                migrations.RenameIndex(
                    model_name='remedytracking',
                    new_name='remedy_trac_user_id_d27392_idx',
                    old_name='remedy_trac_user_id_3f8b4a_idx',
                ),
                migrations.RenameIndex(
                    model_name='remedytracking',
                    new_name='remedy_trac_remedy__aef8b5_idx',
                    old_name='remedy_trac_remedy__4e8b4a_idx',
                ),
            ],
            database_operations=[],
        ),
    ]